# Generated by Django 3.1.3 on 2020-11-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribermail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(error_messages={'unique': 'An account exists with this email.'}, max_length=254, unique=True, verbose_name='email address')),
            ],
        ),
    ]
