# Generated by Django 3.1.3 on 2020-11-24 12:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_smssentphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusform',
            name='pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='smssentphone',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
