# Generated by Django 3.1.3 on 2020-11-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20201124_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smssentphone',
            name='message_id',
            field=models.CharField(max_length=50),
        ),
    ]
