# Generated by Django 3.1.3 on 2020-11-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20201124_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusform',
            name='landmark',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contactusform',
            name='preference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
