# Generated by Django 3.1.3 on 2021-03-26 13:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20201129_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinUsForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('domain', models.CharField(blank=True, max_length=50, null=True)),
                ('experience', models.BooleanField()),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SMSSentPhone',
        ),
        migrations.RenameField(
            model_name='contactusform',
            old_name='area',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='contactusform',
            old_name='name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='contactusform',
            old_name='preference',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contactusform',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactusform',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='contactusform',
            name='orderlist',
        ),
        migrations.RemoveField(
            model_name='contactusform',
            name='pincode',
        ),
        migrations.AddField(
            model_name='contactusform',
            name='domain',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactusform',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='contactusform',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
