# Generated by Django 3.1.3 on 2021-03-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20210326_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinusform',
            name='experience',
            field=models.CharField(max_length=30),
        ),
    ]
